name: CI for Trash Classification

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        pip install -r requirements.txt

    - name: Run the model
      run: |
        jupyter nbconvert --to notebook --execute trash_classification.ipynb
